# Generated by Django 2.2.1 on 2019-06-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='contributor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='address',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
